// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package generator

import "reflect"

var Types = map[string]reflect.Type{
	"Field": reflect.TypeOf((*Field)(nil)).Elem(),
	"Options": reflect.TypeOf((*Options)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

