// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package model_manage

import "reflect"

var Types = map[string]reflect.Type{
	"Department": reflect.TypeOf((*Department)(nil)).Elem(),
	"Dict": reflect.TypeOf((*Dict)(nil)).Elem(),
	"DictData": reflect.TypeOf((*DictData)(nil)).Elem(),
	"DictDataArray": reflect.TypeOf((*DictDataArray)(nil)).Elem(),
	"Message": reflect.TypeOf((*Message)(nil)).Elem(),
	"MessageSend": reflect.TypeOf((*MessageSend)(nil)).Elem(),
	"Permission": reflect.TypeOf((*Permission)(nil)).Elem(),
	"Role": reflect.TypeOf((*Role)(nil)).Elem(),
	"Setting": reflect.TypeOf((*Setting)(nil)).Elem(),
	"Task": reflect.TypeOf((*Task)(nil)).Elem(),
	"User": reflect.TypeOf((*User)(nil)).Elem(),
	"WxUser": reflect.TypeOf((*WxUser)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

