// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package view_model

import "reflect"

var Types = map[string]reflect.Type{
	"BaseViewModel": reflect.TypeOf((*BaseViewModel)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

