// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package view_model_manage

import "reflect"

var Types = map[string]reflect.Type{
	"VM_Department": reflect.TypeOf((*VM_Department)(nil)).Elem(),
	"VM_Dict": reflect.TypeOf((*VM_Dict)(nil)).Elem(),
	"VM_DictData": reflect.TypeOf((*VM_DictData)(nil)).Elem(),
	"VM_Message": reflect.TypeOf((*VM_Message)(nil)).Elem(),
	"VM_MessageSend": reflect.TypeOf((*VM_MessageSend)(nil)).Elem(),
	"VM_Permission": reflect.TypeOf((*VM_Permission)(nil)).Elem(),
	"VM_Role": reflect.TypeOf((*VM_Role)(nil)).Elem(),
	"VM_Role_EditDefault": reflect.TypeOf((*VM_Role_EditDefault)(nil)).Elem(),
	"VM_Role_EditRoleDep": reflect.TypeOf((*VM_Role_EditRoleDep)(nil)).Elem(),
	"VM_Role_EditRolePerms": reflect.TypeOf((*VM_Role_EditRolePerms)(nil)).Elem(),
	"VM_Task": reflect.TypeOf((*VM_Task)(nil)).Elem(),
	"VM_User": reflect.TypeOf((*VM_User)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

