// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package model

import "reflect"

var Types = map[string]reflect.Type{
	"DBModel": reflect.TypeOf((*DBModel)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
	"ModelDBFields": reflect.ValueOf(&ModelDBFields),
}

var Consts = map[string]reflect.Value{
}

