// Code generated by hero.
// source: D:\GoProjects\github.com/anden007/afocus-godf\Backend\src\generate\template\controller.tpl
// DO NOT EDIT!
package template

import "bytes"

func Controller(pkgCode string, model string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package controller_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`

import (
	"github.com/anden007/afocus-godf/src/interfaces/interface_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`"
	"github.com/anden007/afocus-godf/src/lib"
	"github.com/anden007/afocus-godf/src/model/model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`"
	"github.com/anden007/afocus-godf/src/web/view_model/view_model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`"
	"github.com/imdario/mergo"
	jsoniter "github.com/json-iterator/go"
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/mvc"
	"github.com/google/uuid"
	"strings"
)

type `)
	buffer.WriteString(model)
	buffer.WriteString(`Controller struct {
	Ctx         iris.Context
	JsonEncoder jsoniter.API
	Service     interface_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.I`)
	buffer.WriteString(model)
	buffer.WriteString(`Service
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) BeforeActivation(b mvc.BeforeActivation) {
	b.Handle("POST", "/add", "Add")
	b.Handle("DELETE", "/delByIds/{ids:string}", "DelByIds")
	b.Handle("POST", "/edit", "Edit")
	b.Handle("GET", "/getById/{id:string}", "GetById")
	b.Handle("GET", "/getAll", "GetAll")
	b.Handle("GET", "/getByCondition", "GetByCondition")
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) AfterActivation(a mvc.AfterActivation) {
	if m.Service == nil {
		panic("`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller中的Service尚未注册！")
	}
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) Add() mvc.Result {
	success := true
	message := ""
	vModel := view_model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.VM_`)
	buffer.WriteString(model)
	buffer.WriteString(`{}
	err := lib.ReadBody(m.Ctx, m.JsonEncoder, &vModel)
	if err == nil {
		vModel.`)
	buffer.WriteString(model)
	buffer.WriteString(`.Id = lib.NewGuid()
		err = m.Service.Add(vModel.`)
	buffer.WriteString(model)
	buffer.WriteString(`)
	}
	if err != nil {
		success = false
		message = err.Error()
	}
	return mvc.Response{
		Object: iris.Map{"success": success, "message": message},
	}
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) DelByIds(ids string) mvc.Result {
	success := true
	message := ""
	toDelIdArray := []uuid.UUID{}
	toDelIds := strings.Split(ids, ",")
	for _, idStr := range toDelIds {
		id, _ := uuid.Parse(idStr)
		toDelIdArray = append(toDelIdArray, id)
	}
	err := m.Service.DelByIds(toDelIdArray)
	if err != nil {
		success = false
		message = err.Error()
	}
	return mvc.Response{
		Object: iris.Map{"success": success, "message": message},
	}
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) Edit() mvc.Result {
	success := true
	message := ""
	vModel := view_model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.VM_`)
	buffer.WriteString(model)
	buffer.WriteString(`{}
	err := lib.ReadBody(m.Ctx, m.JsonEncoder, &vModel)
	if err == nil {
		err = m.Service.Edit(vModel.`)
	buffer.WriteString(model)
	buffer.WriteString(`)
	}
	if err != nil {
		success = false
		message = err.Error()
	}
	return mvc.Response{
		Object: iris.Map{"success": success, "message": message},
	}
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) GetById(id string) mvc.Result {
	success := true
	message := ""
	Id, _ := uuid.Parse(id)
	result, err := m.Service.GetById(Id)
	if err != nil {
		success = false
		message = err.Error()
	}
	jsonStr, _ := m.JsonEncoder.Marshal(iris.Map{"success": success, "message": message, "result": result})
	return mvc.Response{
		ContentType: "application/json;charset=UTF-8",
		Text:        string(jsonStr),
	}
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) GetAll() mvc.Result {
	success := true
	message := ""
	result, err := m.Service.GetAll()
	if err != nil {
		success = false
		message = err.Error()
	}
	jsonStr, _ := m.JsonEncoder.Marshal(iris.Map{"success": success, "message": message, "result": result})
	return mvc.Response{
		ContentType: "application/json;charset=UTF-8",
		Text:        string(jsonStr),
	}
}

func (m *`)
	buffer.WriteString(model)
	buffer.WriteString(`Controller) GetByCondition() mvc.Result {
	success := true
	message := ""
	var total int64 = 0
	var dbResult []model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.`)
	buffer.WriteString(model)
	buffer.WriteString(`
	var err error
	condition := m.Ctx.URLParams()
	dbResult, total, err = m.Service.GetByCondition(condition)
	var result []view_model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.VM_`)
	buffer.WriteString(model)
	buffer.WriteString(`
	for i := 0; i < len(dbResult); i++ {
		des := view_model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.VM_`)
	buffer.WriteString(model)
	buffer.WriteString(`{}
		err = mergo.Merge(&des.`)
	buffer.WriteString(model)
	buffer.WriteString(`, dbResult[i], mergo.WithOverride, mergo.WithTransformers(&lib.UUIDTransformer{}))
		if err == nil {
			err = des.FromDB()
		}
		result = append(result, des)
	}
	if err != nil {
		success = false
		message = err.Error()
	}
	jsonStr, _ := m.JsonEncoder.MarshalToString(iris.Map{"success": success, "message": message, "result": iris.Map{"content": result, "totalElements": total}})
	return mvc.Response{
		ContentType: "application/json;charset=UTF-8",
		Text:        jsonStr,
	}
}
`)

}
