// Code generated by hero.
// source: D:\GoProjects\github.com/anden007/afocus-godf\Backend\src\generate\template\di.tpl
// DO NOT EDIT!
package template

import "bytes"

func DI(pkgCode string, model string, buffer *bytes.Buffer) {
	buffer.WriteString(`
// +build wireinject
// The build tag makes sure the stub is not built in the final build.

package di

import (
	"github.com/anden007/afocus-godf/src/interfaces"
	"github.com/anden007/afocus-godf/src/interfaces/interface_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`"
	"github.com/anden007/afocus-godf/src/repositories/repository_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`"
	"github.com/anden007/afocus-godf/src/services/service_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`"
	"github.com/google/wire"
)

var `)
	buffer.WriteString(model)
	buffer.WriteString(`Service_Set = wire.NewSet(service_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.New`)
	buffer.WriteString(model)
	buffer.WriteString(`Service, LruCache_SingleSet, repository_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.New`)
	buffer.WriteString(model)
	buffer.WriteString(`Repository, wire.Bind(new(interface_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.I`)
	buffer.WriteString(model)
	buffer.WriteString(`Service), new(*service_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.`)
	buffer.WriteString(model)
	buffer.WriteString(`Service)))

func Get`)
	buffer.WriteString(model)
	buffer.WriteString(`Service() interface_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.I`)
	buffer.WriteString(model)
	buffer.WriteString(`Service {
	panic(wire.Build(`)
	buffer.WriteString(model)
	buffer.WriteString(`Service_Set))
}

func init() {
	container := interfaces.DI()
	container.Get`)
	buffer.WriteString(model)
	buffer.WriteString(`Service = Get`)
	buffer.WriteString(model)
	buffer.WriteString(`Service
}
`)

}
