// Code generated by hero.
// source: D:\GoProjects\github.com/anden007/afocus-godf\Backend\src\generate\template\interface.tpl
// DO NOT EDIT!
package template

import "bytes"

func InterFace(pkgCode string, model string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package interface_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`

import (
	"github.com/anden007/afocus-godf/src/model/model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`"
	"github.com/google/uuid"
)

type I`)
	buffer.WriteString(model)
	buffer.WriteString(`Service interface {
	Add(entity model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.`)
	buffer.WriteString(model)
	buffer.WriteString(`) (err error)
	DelByIds(ids []uuid.UUID ) (err error)
	Edit(entity model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.`)
	buffer.WriteString(model)
	buffer.WriteString(`) (err error)
	Updates(id uuid.UUID , fieldValues map[string]interface{}) (err error)
	GetAll() (result []model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.`)
	buffer.WriteString(model)
	buffer.WriteString(`, err error)
	GetById(id uuid.UUID) (result model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.`)
	buffer.WriteString(model)
	buffer.WriteString(`, err error)
	GetByCondition(condition map[string]string) (result []model_`)
	buffer.WriteString(pkgCode)
	buffer.WriteString(`.`)
	buffer.WriteString(model)
	buffer.WriteString(`, total int64, err error)
}
`)

}
