// Code generated by hero.
// source: D:\GoProjects\github.com/anden007/afocus-godf\Backend\src\web\template\tree.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/anden007/afocus-godf/src/web/view_model/generator"

	"github.com/shiyanhui/hero"
)

type TreeOption struct {
	RowNum          int
	SearchSize      int
	HideSearch      bool
	ModalWidth      string
	Width           string
	ToQuill         bool
	WangEditorWidth string
	QuillWidth      string
	ApiName         string
	Upload          bool
	UploadThumb     bool
	WangEditor      bool
	Quill           bool
	DaterangeSearch bool
	Password        bool
	VueName         string
	Api             bool
	ItemWidth       string
	EditWidth       string
	Span            int
}

func Tree(fields []generator.Field, firstTwo []generator.Field, rest []generator.Field, options TreeOption, buffer *bytes.Buffer) {
	buffer.WriteString(`
<template>
  <div class="search">
    <Card>
      <Row class="operation">
        <Button @click="add" type="primary" icon="md-add">添加子节点</Button>
        <Button @click="addRoot" icon="md-add">添加一级节点</Button>
        <Button @click="delAll" icon="md-trash">批量删除</Button>
        <Button @click="getParentList" icon="md-refresh">刷新</Button>
        <i-switch v-model="strict" size="large" style="margin-left:5px">
          <span slot="open">级联</span>
          <span slot="close">单选</span>
        </i-switch>
      </Row>
      <Row type="flex" justify="start">
        <Col span="6">
          <Alert show-icon>
            当前选择编辑：
            <span class="select-title">{{editTitle}}</span>
            <a class="select-clear" v-if="form.id" @click="cancelEdit">取消选择</a>
          </Alert>
          <Input
            v-model="searchKey"
            suffix="ios-search"
            @on-change="search"
            placeholder="输入节点名搜索"
            clearable
          />
          <div class="tree-bar" :style="{maxHeight: maxHeight}">
            <Tree
              ref="tree"
              :data="data"
              :load-data="loadData"
              show-checkbox
              @on-check-change="changeSelect"
              @on-select-change="selectTree"
              :check-strictly="!strict"
            ></Tree>
            <Spin size="large" fix v-if="loading"></Spin>
          </div>
        </Col>
        <Col span="`)
	hero.FormatInt(int64(options.Span), buffer)
	buffer.WriteString(`" style="margin-left:10px">
          <Form ref="form" :model="form" :label-width="100" :rules="formValidate" `)
	if options.RowNum > 1 {
		buffer.WriteString(`inline`)
	}
	buffer.WriteString(`>
            <FormItem label="上级节点" prop="parentTitle">
              <div style="display:flex;width:`)
	buffer.WriteString(options.Width)
	buffer.WriteString(`">
                <Input v-model="form.parentTitle" readonly style="margin-right:10px;"/>
                <Poptip transfer trigger="click" placement="right-start" title="选择上级部门" width="250">
                  <Button icon="md-list">选择部门</Button>
                  <div slot="content" style="position:relative;min-height:5vh">
                    <Tree :data="dataEdit" :load-data="loadData" @on-select-change="selectTreeEdit"></Tree>
                    <Spin size="large" fix v-if="loadingEdit"></Spin>
                  </div>
                </Poptip>
              </div>
            </FormItem>
            <FormItem label="名称" prop="title">
              <Input v-model="form.title" style="width:`)
	buffer.WriteString(options.Width)
	buffer.WriteString(`"/>
            </FormItem>
            `)

	for _, item := range fields {
		if item.Editable {

			buffer.WriteString(`
            <FormItem label="`)
			buffer.WriteString(item.Name)
			buffer.WriteString(`" prop="`)
			buffer.WriteString(item.Field)
			buffer.WriteString(`" `)
			if options.RowNum > 1 && (item.Type == "switch" || item.Type == "radio") {
				buffer.WriteString(`style="width:`)
				buffer.WriteString(options.ItemWidth)
				buffer.WriteString(`"`)
			}
			if item.Type == "wangEditor" || item.Type == "quill" {
				buffer.WriteString(`class="form-`)
				buffer.WriteString(item.Type)
				buffer.WriteString(`"`)
			}
			buffer.WriteString(`>
              `)

			if item.Type == "text" {

				buffer.WriteString(`
              <Input v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"/>
              `)

			}

			if item.Type == "select" {

				buffer.WriteString(`
              <Select v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`">
                <Option value="0">请自行编辑下拉菜单</Option>
              </Select>
              `)

			}

			if item.Type == "number" {

				buffer.WriteString(`
              <InputNumber v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"></InputNumber>
              `)

			}

			if item.Type == "switch" {

				buffer.WriteString(`
              <i-switch v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`"></i-switch>
              `)

			}

			if item.Type == "radio" {

				buffer.WriteString(`
              <RadioGroup v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`">
                <Radio label="0">请自行编辑单选框</Radio>
                <Radio label="1">请自行编辑单选框</Radio>
              </RadioGroup>
              `)

			}

			if item.Type == "date" {

				buffer.WriteString(`
              <DatePicker type="date" v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"></DatePicker>
              `)

			}

			if item.Type == "daterange" {

				buffer.WriteString(`
              <DatePicker type="daterange" v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"></DatePicker>
              `)

			}

			if item.Type == "time" {

				buffer.WriteString(`
              <TimePicker type="time" v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"></TimePicker>
              `)

			}

			if item.Type == "area" {

				buffer.WriteString(`
              <al-cascader v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" data-type="code" level="`)
				buffer.WriteString(item.Level)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"/>
              `)

			}

			if item.Type == "slider" {

				buffer.WriteString(`
              <Slider v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"></Slider>
              `)

			}

			if item.Type == "upload" {

				buffer.WriteString(`
              <upload-pic-input v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.EditWidth)
				buffer.WriteString(`"></upload-pic-input>
              `)

			}

			if item.Type == "uploadThumb" {

				buffer.WriteString(`
              <uploadThumb v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" multiple style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></uploadThumb>
              `)

			}

			if item.Type == "wangEditor" && !options.ToQuill {

				buffer.WriteString(`
              <wangEditor v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.WangEditorWidth)
				buffer.WriteString(`"></wangEditor>
              `)

			}

			if item.Type == "quill" || (item.Type == "wangEditor" && options.ToQuill) {

				buffer.WriteString(`
              <quill v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.QuillWidth)
				buffer.WriteString(`"></quill>
              `)

			}

			if item.Type == "password" {

				buffer.WriteString(`
              <password v-model="form.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></password>
              `)

			}

			buffer.WriteString(`
            </FormItem>
            `)

		}
	}

	buffer.WriteString(`
            <FormItem label="排序值" prop="sortOrder" style="width:`)
	buffer.WriteString(options.ItemWidth)
	buffer.WriteString(`">
              <Poptip trigger="hover" placement="right" content="值越小越靠前，支持小数">
                <InputNumber :max="1000" :min="0" v-model="form.sortOrder"></InputNumber>
              </Poptip>
            </FormItem>
            <br>
            <Form-item>
              <Button
                @click="submitEdit"
                :loading="submitLoading"
                type="primary"
                icon="ios-create-outline"
                style="margin-right:5px"
              >修改并保存</Button>
              <Button @click="handleReset">重置</Button>
            </Form-item>
          </Form>
        </Col>
      </Row>
    </Card>

    <Modal :title="modalTitle" v-model="modalVisible" :mask-closable="false" :width="`)
	buffer.WriteString(options.ModalWidth)
	buffer.WriteString(`">
      <Form ref="formAdd" :model="formAdd" :label-width="100" :rules="formValidate" label-position="left" `)
	if options.RowNum > 1 {
		buffer.WriteString(`inline`)
	}
	buffer.WriteString(`>
        <div v-if="showParent">
          <FormItem label="上级节点：">{{form.title}}</FormItem>
        </div>
        <FormItem label="名称" prop="title">
          <Input v-model="formAdd.title" style="width:`)
	buffer.WriteString(options.Width)
	buffer.WriteString(`"/>
        </FormItem>
        `)

	for _, item := range fields {
		if item.Editable {

			buffer.WriteString(`
        <FormItem label="`)
			buffer.WriteString(item.Name)
			buffer.WriteString(`" prop="`)
			buffer.WriteString(item.Field)
			buffer.WriteString(`" `)
			if options.RowNum > 1 && (item.Type == "number" || item.Type == "switch" || item.Type == "radio") {
				buffer.WriteString(`style="width:`)
				buffer.WriteString(options.ItemWidth)
				buffer.WriteString(`"`)
			}
			if item.Type == "wangEditor" || item.Type == "quill" {
				buffer.WriteString(`class="form-`)
				buffer.WriteString(item.Type)
				buffer.WriteString(`"`)
			}
			buffer.WriteString(`>
          `)

			if item.Type == "text" {

				buffer.WriteString(`
          <Input v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"/>
          `)

			}

			if item.Type == "select" {

				buffer.WriteString(`
          <Select v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`">
            <Option value="0">请自行编辑下拉菜单</Option>
          </Select>
          `)

			}

			if item.Type == "number" {

				buffer.WriteString(`
          <InputNumber v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`"></InputNumber>
          `)

			}

			if item.Type == "switch" {

				buffer.WriteString(`
          <i-switch v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`"></i-switch>
          `)

			}

			if item.Type == "radio" {

				buffer.WriteString(`
          <RadioGroup v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`">
            <Radio label="0">请自行编辑单选框</Radio>
            <Radio label="1">请自行编辑单选框</Radio>
          </RadioGroup>
          `)

			}

			if item.Type == "date" {

				buffer.WriteString(`
          <DatePicker type="date" v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></DatePicker>
          `)

			}

			if item.Type == "daterange" {

				buffer.WriteString(`
          <DatePicker type="daterange" v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></DatePicker>
          `)

			}

			if item.Type == "time" {

				buffer.WriteString(`
          <TimePicker type="time" v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></TimePicker>
          `)

			}

			if item.Type == "area" {

				buffer.WriteString(`
          <al-cascader v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" data-type="code" level="`)
				buffer.WriteString(item.Level)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"/>
          `)

			}

			if item.Type == "slider" {

				buffer.WriteString(`
          <Slider v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></Slider>
          `)

			}

			if item.Type == "upload" {

				buffer.WriteString(`
          <upload-pic-input v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></upload-pic-input>
          `)

			}

			if item.Type == "uploadThumb" {

				buffer.WriteString(`
          <uploadThumb v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" multiple style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></uploadThumb>
          `)

			}

			if item.Type == "wangEditor" && !options.ToQuill {

				buffer.WriteString(`
          <wangEditor id="editor2" v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.WangEditorWidth)
				buffer.WriteString(`"></wangEditor>
          `)

			}

			if item.Type == "quill" || (item.Type == "wangEditor" && options.ToQuill) {

				buffer.WriteString(`
          <quill id="editor2" v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.QuillWidth)
				buffer.WriteString(`"></quill>
          `)

			}

			if item.Type == "password" {

				buffer.WriteString(`
          <password v-model="formAdd.`)
				buffer.WriteString(item.Field)
				buffer.WriteString(`" style="width:`)
				buffer.WriteString(options.Width)
				buffer.WriteString(`"></password>
          `)

			}

			buffer.WriteString(`
        </FormItem>
        `)

		}
	}

	buffer.WriteString(`
        <FormItem label="排序值" prop="sortOrder" style="width:`)
	buffer.WriteString(options.ItemWidth)
	buffer.WriteString(`">
          <Poptip trigger="hover" placement="right" content="值越小越靠前，支持小数">
            <InputNumber :max="1000" :min="0" v-model="formAdd.sortOrder"></InputNumber>
          </Poptip>
        </FormItem>
      </Form>
      <div slot="footer">
        <Button type="text" @click="modalVisible=false">取消</Button>
        <Button type="primary" :loading="submitLoading" @click="submitAdd">提交</Button>
      </div>
    </Modal>
  </div>
</template>

<script>
`)

	if options.Api {

		buffer.WriteString(`
// 根据你的实际请求api.js位置路径修改
import { init`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`, load`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`, add`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`, edit`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`, delete`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`, search`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(` } from "@/api/index";
import moment from "moment";
`)

	}

	if options.Upload {

		buffer.WriteString(`
import uploadPicInput from "@/views/my-components/xboot/upload-pic-input";
`)

	}

	if options.UploadThumb {

		buffer.WriteString(`
import uploadThumb from "@/views/my-components/xboot/upload-pic-thumb";
`)

	}

	if options.WangEditor && !options.ToQuill {

		buffer.WriteString(`
import wangEditor from "@/views/my-components/xboot/editor";
`)

	}

	if options.Quill || options.ToQuill {

		buffer.WriteString(`
import quill from "@/views/my-components/xboot/quill";
`)

	}

	if options.Password {

		buffer.WriteString(`
import password from "@/views/my-components/xboot/set-password";
`)

	}

	buffer.WriteString(`
export default {
  name: "`)
	buffer.WriteString(options.VueName)
	buffer.WriteString(`",
  components: {
    `)

	if options.Upload {

		buffer.WriteString(`
    uploadPicInput,
    `)

	}

	if options.UploadThumb {

		buffer.WriteString(`
    uploadThumb,
    `)

	}

	if options.WangEditor && !options.ToQuill {

		buffer.WriteString(`
    wangEditor,
    `)

	}

	if options.Quill || options.ToQuill {

		buffer.WriteString(`
    quill,
    `)

	}

	if options.Password {

		buffer.WriteString(`
    password,
    `)

	}

	buffer.WriteString(`
  },
  data() {
    return {
      maxHeight: "500px",
      strict: true,
      loading: false, // 树加载状态
      loadingEdit: false, // 编辑上级树加载状态
      modalVisible: false, // 添加显示
      selectList: [], // 多选数据
      selectCount: 0, // 多选计数
      showParent: false, // 显示上级标识
      modalTitle: "", // 添加标题
      editTitle: "", // 编辑节点名称
      searchKey: "", // 搜索树
      form: {
        // 编辑对象初始化数据
        id: "",
        title: "",
        parentId: "",
        parentTitle: "",
        sortOrder: 0,
        `)

	for _, item := range fields {
		if item.Editable {

			if item.Type == "switch" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: true,
        `)
			} else if item.Type == "number" || item.Type == "slider" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: 0,
        `)
			} else if item.Type == "area" || item.Type == "uploadThumb" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [],
        `)
			} else {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: "",
        `)
			}

		}
	}

	buffer.WriteString(`
      },
      formAdd: {
        // 添加对象初始化数据
      },
      formValidate: {
        // 表单验证规则
        title: [{ required: true, message: "不能为空", trigger: "blur" }],
        sortOrder: [
          {
            required: true,
            type: "number",
            message: "排序值不能为空",
            trigger: "blur"
          }
        ],
        `)

	for _, item := range fields {
		if item.Editable && item.Validate {

			if item.Type == "daterange" || item.Type == "area" || item.Type == "uploadThumb" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [{ type: "array", required: true, message: "不能为空", trigger: "blur" }],
        `)
			} else if item.Type == "date" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [{ required: true, message: "不能为空", trigger: "blur", pattern: /.+/ }],
        `)
			} else if item.Type == "number" || item.Type == "slider" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [{ type: "number", required: true, message: "不能为空", trigger: "blur" }],
        `)
			} else if item.Type == "switch" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [{ type: "boolean", required: true, message: "不能为空", trigger: "blur" }],
        `)
			} else {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [{ required: true, message: "不能为空", trigger: "blur" }],
        `)
			}

		}
	}

	buffer.WriteString(`
      },
      submitLoading: false,
      data: [],
      dataEdit: []
    };
  },
  methods: {
    init() {
      // 初始化一级节点
      this.getParentList();
      // 初始化一级节点为编辑上级节点使用
      this.getParentListEdit();
    },
    getParentList() {
      `)

	if options.Api {

		buffer.WriteString(`
      this.loading = true;
      init`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`().then(res => {
        this.loading = false;
        if (res.success) {
          res.result.forEach(function(e) {
            if (e.isParent) {
              e.loading = false;
              e.children = [];
            }
          });
          this.data = res.result;
        }
      });
      `)

	} else {

		buffer.WriteString(`
      // this.loading = true;
      // this.getRequest("一级数据请求路径，如/tree/getByParentId/0").then(res => {
      //   this.loading = false;
      //   if (res.success) {
      //     res.result.forEach(function(e) {
      //       if (e.isParent) {
      //         e.loading = false;
      //         e.children = [];
      //       }
      //     });
      //     this.data = res.result;
      //   }
      // });
      // 模拟请求成功
      this.data = [
      ];
      `)

	}

	buffer.WriteString(`
    },
    getParentListEdit() {
      `)

	if options.Api {

		buffer.WriteString(`
      this.loadingEdit = true;
      init`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`().then(res => {
        this.loadingEdit = false;
        if (res.success) {
          res.result.forEach(function(e) {
            if (e.isParent) {
              e.loading = false;
              e.children = [];
            }
          });
          // 头部加入一级
          let first = {
            id: "0",
            title: "一级节点"
          };
          res.result.unshift(first);
          this.dataEdit = res.result;
        }
      });
      `)

	} else {

		buffer.WriteString(`
      // this.loadingEdit = true;
      // this.getRequest("/tree/getByParentId/0").then(res => {
      //   this.loadingEdit = false;
      //   if (res.success) {
      //     res.result.forEach(function(e) {
      //       if (e.isParent) {
      //         e.loading = false;
      //         e.children = [];
      //       }
      //     });
      //     // 头部加入一级
      //     let first = {
      //       id: "0",
      //       title: "一级节点"
      //     };
      //     res.result.unshift(first);
      //     this.dataEdit = res.result;
      //   }
      // });
      // 模拟请求成功
      this.dataEdit = [
      ];
      `)

	}

	buffer.WriteString(`
    },
    loadData(item, callback) {
      `)

	if options.Api {

		buffer.WriteString(`
      load`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`(item.id).then(res => {
        if (res.success) {
          res.result.forEach(function(e) {
            if (e.isParent) {
              e.loading = false;
              e.children = [];
            }
          });
          callback(res.result);
        }
      });
      `)

	} else {

		buffer.WriteString(`
      // 异步加载树子节点数据
      // this.getRequest("请求路径，如/tree/getByParentId/" + item.id).then(res => {
      //   if (res.success) {
      //     res.result.forEach(function(e) {
      //       if (e.isParent) {
      //         e.loading = false;
      //         e.children = [];
      //       }
      //     });
      //     callback(res.result);
      //   }
      // });
      `)

	}

	buffer.WriteString(`
    },
    search() {
      // 搜索树
      if (this.searchKey) {
        `)

	if options.Api {

		buffer.WriteString(`
        this.loading = true;
        search`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`({ title: this.searchKey %>).then(res => {
          this.loading = false;
          if (res.success) {
            this.data = res.result;
          }
        });
        `)

	} else {

		buffer.WriteString(`
        // 模拟请求
        // this.loading = true;
        // this.getRequest("搜索请求路径", { title: this.searchKey }).then(res => {
        //   this.loading = false;
        //   if (res.success) {
        //     this.data = res.result;
        //   }
        // });
        // 模拟请求成功
        this.data = [
        ];
        `)

	}

	buffer.WriteString(`
      } else {
        // 为空重新加载
        this.getParentList();
      }
    },
    selectTree(v) {
      if (v.length > 0) {
        // 转换null为""
        for (let attr in v[0]) {
          if (v[0][attr] === null) {
            v[0][attr] = "";
          }
        }
        let str = JSON.stringify(v[0]);
        let data = JSON.parse(str);
        this.form = data;
        this.editTitle = data.title;
      } else {
        this.cancelEdit();
      }
    },
    cancelEdit() {
      let data = this.$refs.tree.getSelectedNodes()[0];
      if (data) {
        data.selected = false;
      }
      this.$refs.form.resetFields();
      this.form.id = "";
      this.editTitle = "";
    },
    selectTreeEdit(v) {
      if (v.length > 0) {
        // 转换null为""
        for (let attr in v[0]) {
          if (v[0][attr] === null) {
            v[0][attr] = "";
          }
        }
        let str = JSON.stringify(v[0]);
        let data = JSON.parse(str);
        this.form.parentId = data.id;
        this.form.parentTitle = data.title;
      }
    },
    handleReset() {
      this.$refs.form.resetFields();
      this.form.status = 0;
    },
    submitEdit() {
      this.$refs.form.validate(valid => {
        if (valid) {
        `)
	for _, item := range fields {
		if item.Type == "date" {
			buffer.WriteString(`
          this.form.`)
			buffer.WriteString(item.Field)
			buffer.WriteString(` = moment(this.form.`)
			buffer.WriteString(item.Field)
			buffer.WriteString(`).format("YYYY-MM-DD HH:mm:ss");
        `)
		}
	}
	buffer.WriteString(`
          if (!this.form.id) {
            this.$Message.warning("请先点击选择要修改的节点");
            return;
          }
          this.submitLoading = true;
          `)

	if options.Api {

		buffer.WriteString(`
          edit`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`(this.form).then(res => {
          this.submitLoading = false;
          if (res.success) {
            this.$Message.success("编辑成功");
              this.init();
              this.modalVisible = false;
            }
          });
          `)

	} else {

		buffer.WriteString(`
          // this.postRequest("请求路径，如/tree/edit", this.form).then(res => {
          //   this.submitLoading = false;
          //   if (res.success) {
          //     this.$Message.success("编辑成功");
          //     this.init();
          //     this.modalVisible = false;
          //   }
          // });
          // 模拟成功
          this.submitLoading = false;
          this.$Message.success("编辑成功");
          this.modalVisible = false;
          `)

	}

	buffer.WriteString(`
        }
      });
    },
    submitAdd() {
      this.$refs.formAdd.validate(valid => {
        if (valid) {
          this.submitLoading = true;
          `)

	if options.Api {

		buffer.WriteString(`
          add`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`(this.formAdd).then(res => {
            this.submitLoading = false;
            if (res.success) {
              this.$Message.success("添加成功");
              this.init();
              this.modalVisible = false;
            }
          });
          `)

	} else {

		buffer.WriteString(`
          // this.postRequest("请求路径，如/tree/add", this.formAdd).then(res => {
          //   this.submitLoading = false;
          //   if (res.success) {
          //     this.$Message.success("添加成功");
          //     this.init();
          //     this.modalVisible = false;
          //   }
          // });
          // 模拟成功
          this.submitLoading = false;
          this.$Message.success("添加成功");
          this.modalVisible = false;
          `)

	}

	buffer.WriteString(`
        }
      });
    },
    add() {
      if (this.form.id == "" || this.form.id == null) {
        this.$Message.warning("请先点击选择一个节点");
        return;
      }
      this.modalTitle = "添加子节点";
      this.showParent = true;
      this.formAdd = {
        parentId: this.form.id,
        sortOrder: 0,
        `)

	for _, item := range fields {
		if item.Editable {

			if item.Type == "switch" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: true,
        `)
			} else if item.Type == "number" || item.Type == "slider" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: 0,
        `)
			} else if item.Type == "area" || item.Type == "uploadThumb" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [],
        `)
			} else {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: "",
        `)
			}

		}
	}

	buffer.WriteString(`
      };
      this.modalVisible = true;
    },
    addRoot() {
      this.modalTitle = "添加一级节点";
      this.showParent = false;
      this.formAdd = {
        parentId: 0,
        sortOrder: 0,
        title: "",
        `)

	for _, item := range fields {
		if item.Editable {

			if item.Type == "switch" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: true,
        `)
			} else if item.Type == "number" || item.Type == "slider" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: 0,
        `)
			} else if item.Type == "area" {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: [],
        `)
			} else {
				buffer.WriteString(item.Field)
				buffer.WriteString(`: "",
        `)
			}

		}
	}

	buffer.WriteString(`
      };
      this.modalVisible = true;
    },
    changeSelect(v) {
      this.selectCount = v.length;
      this.selectList = v;
    },
    delAll() {
      if (this.selectCount <= 0) {
        this.$Message.warning("您还未勾选要删除的数据");
        return;
      }
      this.$Modal.confirm({
        title: "确认删除",
        content: "您确认要删除所选的 " + this.selectCount + " 条数据及其下级所有数据?",
        loading: true,
        onOk: () => {
          let ids = "";
          this.selectList.forEach(function(e) {
            ids += e.id + ",";
          });
          ids = ids.substring(0, ids.length - 1);
           `)

	if options.Api {

		buffer.WriteString(`
          delete`)
		buffer.WriteString(options.ApiName)
		buffer.WriteString(`(ids).then(res => {
            this.$Modal.remove();
            if (res.success) {
              this.$Message.success("删除成功");
              this.selectList = [];
              this.selectCount = 0;
              this.cancelEdit();
              this.init();
            }
          });
          `)

	} else {

		buffer.WriteString(`
          // this.deleteRequest("请求路径，如/tree/delByIds/" + ids).then(res => {
          //   this.$Modal.remove();
          //   if (res.success) {
          //     this.$Message.success("删除成功");
          //     this.selectList = [];
          //     this.selectCount = 0;
          //     this.cancelEdit();
          //     this.init();
          //   }
          // });
          // 模拟成功
          this.$Modal.remove();
          this.$Message.success("删除成功");
          this.selectList = [];
          this.selectCount = 0;
          this.cancelEdit();
          `)

	}

	buffer.WriteString(`
        }
      });
    }
  },
  mounted() {
    // 计算高度
    let height = document.documentElement.clientHeight;
    this.maxHeight = Number(height-287) + "px";
    this.init();
  }
};
</script>
<style lang="less">
// 建议引入通用样式 具体路径自行修改 可删除下面样式代码
// @import "../../../styles/tree-common.less";
.search {
    .operation {
        margin-bottom: 2vh;
    }
    .select-title {
        font-weight: 600;
        color: #40a9ff;
    }
    .select-clear {
        margin-left: 10px;
    }
}

.tree-bar {
    overflow: auto;
    margin-top: 5px;
    position: relative;
    min-height: 80px;
}

.tree-bar::-webkit-scrollbar {
    width: 6px;
    height: 6px;
}

.tree-bar::-webkit-scrollbar-thumb {
    border-radius: 4px;
    -webkit-box-shadow: inset 0 0 2px #d1d1d1;
    background: #e4e4e4;
}
</style>`)

}
