// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package model_draw

import "reflect"

var Types = map[string]reflect.Type{
	"Action": reflect.TypeOf((*Action)(nil)).Elem(),
	"Gift": reflect.TypeOf((*Gift)(nil)).Elem(),
	"Player": reflect.TypeOf((*Player)(nil)).Elem(),
	"Result": reflect.TypeOf((*Result)(nil)).Elem(),
	"VerifyResult": reflect.TypeOf((*VerifyResult)(nil)).Elem(),
	"Voucher": reflect.TypeOf((*Voucher)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

